[project]
name = "mcp-hello-world"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gradio[mcp]>=5.30.0",
    "langchain-mcp-adapters>=0.1.1",
    "mcp[cli]>=1.9.1",
    "smolagents[mcp]>=1.16.1",
]
